const ACTION_TYPES = {
  GET_MESSAGES_REQUEST: "GET_MESSAGES_REQUEST",
  SEND_MESSAGE_REQUEST: "SEND_MESSAGE_REQUEST",
  
  GET_MESSAGES_SUCCESS: "GET_MESSAGES_SUCCESS",
  SEND_MESSAGE_SUCCESS: "SEND_MESSAGE_SUCCESS",
  
  GET_MESSAGES_ERROR: "GET_MESSAGES_ERROR",
  SEND_MESSAGE_ERROR: "SEND_MESSAGE_ERROR",
  
  GET_USER_REQUEST: "GET_USER_REQUEST",
  LOGIN_REQUEST: "LOGIN_REQUEST",
  REGISTER_REQUEST: "REGISTER_REQUEST",
  
  GET_USER_SUCCESS: "GET_USER_SUCCESS",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  REGISTER_SUCCESS: "REGISTER_SUCCESS",
  
  GET_USER_ERROR: "GET_USER_ERROR",
  LOGIN_ERROR: "LOGIN_ERROR",
  REGISTER_ERROR: "REGISTER_ERROR",
};

export default ACTION_TYPES;
